# what are the stages we are going to have
stages:
  load_data:
    cmd: python src\load_data.py --config=params.yaml
    deps:  # dependencies
    - src\get_data.py
    - src\load_data.py
    - data_given\WineQT.csv
    outs:
    - data\raw\WineQT.csv

# step 2

  split_data:
    cmd: python src\split_data.py --config=params.yaml
    deps:
    - src\split_data.py
    - data\raw\WineQT.csv
    outs:
    - data\processed\train_WineQT.csv
    - data\processed\test_WineQT.csv

