base:
  project: Wine-Quality-Project
  random_state: 42
  target_col: TARGET

data_source:
  s3_source: data_given\WineQT.csv # take data from here to put in load data

load_data:
  raw_dataset_csv: data\raw\WineQT.csv

split_data:
  train_path: data\processed\train_WineQT.csv
  test_path: data\processed\test_WineQT.csv
  test_size: 0.2

estimators:
  ElasticNet:   # what algorithms we are going to use
    params:
      alpha: 0.88
      l1_ratio: 0.89

model_dir: saved_models



